#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D sourceImage;
layout(set = 0, binding = 1, rgba16f) uniform writeonly image2D destinationImage;

layout(push_constant) uniform PyramidPush {
    uvec4 extents;
} push;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 destinationSize = ivec2(push.extents.zw);
    if (any(greaterThanEqual(pixel, destinationSize)))
        return;
    imageStore(destinationImage, pixel, texelFetch(sourceImage, pixel, 0));
}
