if(WIN32)
    if(VKL_BUILD_CONTROL_TOOL)
        add_subdirectory(vulkan_lab_ctl)
    endif()
    if(VKL_BUILD_ASSET_TOOL)
        add_subdirectory(vulkan_lab_asset_tool)
        if(VKL_ENABLE_ASSET_AUTHORING)
            add_dependencies(VulkanLab VulkanLabAssetTool)
        endif()
    endif()
    if(VKL_BUILD_RENDER_TEST)
        add_subdirectory(vulkan_lab_render_test)
    endif()
endif()
